{"time":"2025-05-30T21:42:41.6241526+08:00","level":"INFO","msg":"stream: starting","core version":"0.19.11","symlink path":"D:\\Courses\\NLP\\NLP2025\\wandb\\run-20250530_214241-7gdfmb1i\\logs\\debug-core.log"}
{"time":"2025-05-30T21:43:04.5022762+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T21:43:27.6282739+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T21:43:53.2001466+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
